### ISSUE TITLE
No `HERE` in the default env variables

### ISSUE THREAD

**Issue by dougxwok2** [shadowmint/rust-pup#1]
`HERE` or `MANIFEST_PATH` should always be the root folder relative to the manifest so we can find temporary files for execution workers.

It shouldn't have to be up to the individual worker to identify it's own root path.

**Comment by shadowmint** [comment]
This is fixed in https://github.com/shadowmint/rust-pup/commit/78c37e886e5e9e9c9b95645cbd1d98c8438364b8, you can now refer to `ACTION_HOME` and `MANIFEST_HOME` in tasks.
